name: new_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.7.2
  flutter_mjpeg: ^2.0.4
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.13.1
  wakelock_plus: ^1.1.6
  flutter_riverpod: ^2.6.1
  amplify_api: ^2.6.0
  amplify_flutter: ^2.6.0
  simple_logger: ^1.10.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  envied: ^1.1.1
  envied_generator: ^1.1.1
  freezed: ^2.5.2
  cached_network_image: ^3.3.1
  http: ^0.13.6
  amazon_cognito_identity_dart_2: ^3.8.1
  flutter_web_auth: ^0.5.0
  jwt_decode: ^0.3.1
  amplify_auth_cognito: ^2.6.0
  amplify_authenticator: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  graphql_codegen: ^1.1.1
  build_runner: ^2.4.11
  riverpod_generator: ^2.3.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
